#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APEX_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

cd "${APEX_ROOT}"
export PATH="${HOME}/local/bin:${PATH}"

APEX_ENABLE_KINEMATICS="${APEX_ENABLE_KINEMATICS:-1}" \
APEX_ENABLE_IMU_LIDAR_FUSION="${APEX_ENABLE_IMU_LIDAR_FUSION:-1}" \
APEX_ENABLE_CURVE_ENTRY_PLANNER="${APEX_ENABLE_CURVE_ENTRY_PLANNER:-0}" \
APEX_ENABLE_PATH_TRACKER="${APEX_ENABLE_PATH_TRACKER:-0}" \
APEX_ENABLE_RECOGNITION_TOUR_PLANNER="${APEX_ENABLE_RECOGNITION_TOUR_PLANNER:-1}" \
APEX_ENABLE_RECOGNITION_TOUR_TRACKER="${APEX_ENABLE_RECOGNITION_TOUR_TRACKER:-1}" \
APEX_ENABLE_CMDVEL_ACTUATION_BRIDGE="${APEX_ENABLE_CMDVEL_ACTUATION_BRIDGE:-1}" \
APEX_ENABLE_MANUAL_CONTROL_BRIDGE="${APEX_ENABLE_MANUAL_CONTROL_BRIDGE:-0}" \
APEX_ENABLE_RECOGNITION_SESSION_MANAGER="${APEX_ENABLE_RECOGNITION_SESSION_MANAGER:-1}" \
APEX_ENABLE_OFFLINE_SUBMAP_REFINER="${APEX_ENABLE_OFFLINE_SUBMAP_REFINER:-1}" \
APEX_STARTUP_COMPAT="${APEX_STARTUP_COMPAT:-safe}" \
APEX_STAGGERED_STARTUP="${APEX_STAGGERED_STARTUP:-1}" \
APEX_SERIAL_WARMUP_S="${APEX_SERIAL_WARMUP_S:-2.0}" \
APEX_LIDAR_STARTUP_SETTLE_S="${APEX_LIDAR_STARTUP_SETTLE_S:-6.0}" \
APEX_NODE_STARTUP_STAGGER_S="${APEX_NODE_STARTUP_STAGGER_S:-0.8}" \
APEX_RAW_POSTCHECK_READY_DELAY_S="${APEX_RAW_POSTCHECK_READY_DELAY_S:-8}" \
APEX_RAW_POSTCHECK_RETRIES="${APEX_RAW_POSTCHECK_RETRIES:-2}" \
APEX_RAW_POSTCHECK_TOPIC_GAP_S="${APEX_RAW_POSTCHECK_TOPIC_GAP_S:-1.0}" \
APEX_SKIP_BUILD="${APEX_SKIP_BUILD:-1}" \
APEX_NANO_PREFLIGHT="${APEX_NANO_PREFLIGHT:-1}" \
./tools/capture/apex_raw_capture_up.sh
