#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APEX_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
REPO_ROOT="$(cd "${APEX_ROOT}/.." && pwd)"
OFFLINE_ROOT="${APEX_OFFLINE_REFINED_ROOT:-${APEX_ROOT}/.apex_runtime/offline_refined_maps}"
RUN_ARG="${1:-latest}"

to_container_path() {
  local host_path="$1"
  case "${host_path}" in
    "${REPO_ROOT}"/*)
      printf '/work/repo/%s\n' "${host_path#"${REPO_ROOT}/"}"
      ;;
    *)
      printf '%s\n' "${host_path}"
      ;;
  esac
}

if [[ "${RUN_ARG}" == "latest" ]]; then
  RUN_DIR="$(ls -1dt "${OFFLINE_ROOT}"/offline_refined_* 2>/dev/null | head -n 1 || true)"
elif [[ "${RUN_ARG}" = /* ]]; then
  RUN_DIR="${RUN_ARG}"
else
  RUN_DIR="${OFFLINE_ROOT%/}/${RUN_ARG}"
fi

if [[ -z "${RUN_DIR}" || ! -d "${RUN_DIR}" ]]; then
  echo "[APEX][ERROR] No offline_refined run found. Checked: ${RUN_DIR:-${OFFLINE_ROOT}}" >&2
  exit 1
fi

for required in map_points_xy.csv path_poses_xyyaw.csv poses.json; do
  if [[ ! -f "${RUN_DIR}/${required}" ]]; then
    echo "[APEX][ERROR] Missing ${RUN_DIR}/${required}" >&2
    exit 1
  fi
done

CONTAINER_RUN_DIR="$(to_container_path "$(cd "${RUN_DIR}" && pwd)")"
CONTAINER_FIXED_MAP_DIR="${CONTAINER_RUN_DIR%/}/fixed_map"

export APEX_ENABLE_KINEMATICS="${APEX_ENABLE_KINEMATICS:-1}"
export APEX_ENABLE_IMU_LIDAR_FUSION="${APEX_ENABLE_IMU_LIDAR_FUSION:-1}"
export APEX_ESTIMATION_BACKEND="${APEX_ESTIMATION_BACKEND:-fixed_map}"
export APEX_ENABLE_CURVE_ENTRY_PLANNER="${APEX_ENABLE_CURVE_ENTRY_PLANNER:-0}"
export APEX_ENABLE_PATH_TRACKER="${APEX_ENABLE_PATH_TRACKER:-0}"
export APEX_ENABLE_RECOGNITION_TOUR_PLANNER="${APEX_ENABLE_RECOGNITION_TOUR_PLANNER:-0}"
export APEX_ENABLE_RECOGNITION_TOUR_TRACKER="${APEX_ENABLE_RECOGNITION_TOUR_TRACKER:-1}"
export APEX_ENABLE_FIXED_MAP_ROUTE_PLANNER="${APEX_ENABLE_FIXED_MAP_ROUTE_PLANNER:-1}"
export APEX_ENABLE_FIXED_MAP_PUBLISHER="${APEX_ENABLE_FIXED_MAP_PUBLISHER:-1}"
export APEX_ENABLE_CMDVEL_ACTUATION_BRIDGE="${APEX_ENABLE_CMDVEL_ACTUATION_BRIDGE:-1}"
export APEX_ENABLE_MANUAL_CONTROL_BRIDGE="${APEX_ENABLE_MANUAL_CONTROL_BRIDGE:-0}"
export APEX_ENABLE_RECOGNITION_SESSION_MANAGER="${APEX_ENABLE_RECOGNITION_SESSION_MANAGER:-0}"
export APEX_ENABLE_OFFLINE_SUBMAP_REFINER="${APEX_ENABLE_OFFLINE_SUBMAP_REFINER:-0}"

export APEX_FIXED_MAP_AUTOBUILD="${APEX_FIXED_MAP_AUTOBUILD:-1}"
export APEX_FIXED_MAP_RUN_DIR="${APEX_FIXED_MAP_RUN_DIR:-${CONTAINER_RUN_DIR}}"
export APEX_FIXED_MAP_DIR="${APEX_FIXED_MAP_DIR:-${CONTAINER_FIXED_MAP_DIR}}"
export APEX_FIXED_MAP_CLEARANCE_M="${APEX_FIXED_MAP_CLEARANCE_M:-0.15}"
export APEX_FIXED_MAP_FRAME_ID="${APEX_FIXED_MAP_FRAME_ID:-odom_imu_lidar_fused}"

export APEX_FUSION_ODOM_TOPIC="${APEX_FUSION_ODOM_TOPIC:-/apex/odometry/fixed_map_localized}"
export APEX_FUSION_PATH_TOPIC="${APEX_FUSION_PATH_TOPIC:-/apex/localization/fixed_map_path}"
export APEX_FUSION_POSE_TOPIC="${APEX_FUSION_POSE_TOPIC:-/apex/localization/fixed_map_pose}"
export APEX_FUSION_LIVE_MAP_TOPIC="${APEX_FUSION_LIVE_MAP_TOPIC:-/apex/localization/fixed_map_live_points}"
export APEX_FUSION_FULL_MAP_TOPIC="${APEX_FUSION_FULL_MAP_TOPIC:-/apex/localization/fixed_map_points}"
export APEX_FUSION_STATUS_TOPIC="${APEX_FUSION_STATUS_TOPIC:-/apex/localization/fixed_map_status}"
export APEX_FUSION_ODOM_FRAME_ID="${APEX_FUSION_ODOM_FRAME_ID:-odom_imu_lidar_fused}"

export APEX_FIXED_MAP_ROUTE_PATH_TOPIC="${APEX_FIXED_MAP_ROUTE_PATH_TOPIC:-/apex/planning/fixed_map_path}"
export APEX_FIXED_MAP_ROUTE_STATUS_TOPIC="${APEX_FIXED_MAP_ROUTE_STATUS_TOPIC:-/apex/planning/fixed_map_status}"
export APEX_FIXED_MAP_GRID_TOPIC="${APEX_FIXED_MAP_GRID_TOPIC:-/apex/fixed_map/grid}"
export APEX_FIXED_MAP_VISUAL_POINTS_TOPIC="${APEX_FIXED_MAP_VISUAL_POINTS_TOPIC:-/apex/fixed_map/visual_points}"
export APEX_FIXED_MAP_RECORDED_PATH_TOPIC="${APEX_FIXED_MAP_RECORDED_PATH_TOPIC:-/apex/fixed_map/route_preview_path}"
export APEX_FIXED_MAP_STATUS_TOPIC="${APEX_FIXED_MAP_STATUS_TOPIC:-/apex/fixed_map/status}"

export APEX_RECOGNITION_TRACKER_PATH_TOPIC="${APEX_RECOGNITION_TRACKER_PATH_TOPIC:-/apex/planning/fixed_map_path}"
export APEX_RECOGNITION_TRACKER_PLANNING_STATUS_TOPIC="${APEX_RECOGNITION_TRACKER_PLANNING_STATUS_TOPIC:-/apex/planning/fixed_map_status}"
export APEX_RECOGNITION_TRACKER_ODOM_TOPIC="${APEX_RECOGNITION_TRACKER_ODOM_TOPIC:-/apex/odometry/fixed_map_localized}"
export APEX_RECOGNITION_TRACKER_FUSION_STATUS_TOPIC="${APEX_RECOGNITION_TRACKER_FUSION_STATUS_TOPIC:-/apex/localization/fixed_map_status}"
export APEX_RECOGNITION_TRACKER_STATUS_TOPIC="${APEX_RECOGNITION_TRACKER_STATUS_TOPIC:-/apex/tracking/fixed_map_status}"
export APEX_RECOGNITION_TRACKER_REQUIRE_ARM="${APEX_RECOGNITION_TRACKER_REQUIRE_ARM:-false}"
export APEX_RECOGNITION_TRACKER_DEFAULT_ARMED="${APEX_RECOGNITION_TRACKER_DEFAULT_ARMED:-true}"
export APEX_RECOGNITION_TRACKER_PUBLISH_UNARMED_ZERO_CMD="${APEX_RECOGNITION_TRACKER_PUBLISH_UNARMED_ZERO_CMD:-false}"
export APEX_RECOGNITION_TRACKER_PATH_STALE_MAX_AGE_S="${APEX_RECOGNITION_TRACKER_PATH_STALE_MAX_AGE_S:-2.0}"
export APEX_RECOGNITION_TRACKER_PATH_STALE_ABORT_HOLD_S="${APEX_RECOGNITION_TRACKER_PATH_STALE_ABORT_HOLD_S:-2.5}"
export APEX_RECOGNITION_TRACKER_REAR_AXLE_OFFSET_X_M="${APEX_RECOGNITION_TRACKER_REAR_AXLE_OFFSET_X_M:-0.0}"
export APEX_RECOGNITION_TRACKER_REAR_AXLE_OFFSET_Y_M="${APEX_RECOGNITION_TRACKER_REAR_AXLE_OFFSET_Y_M:-0.0}"
export APEX_RECOGNITION_TRACKER_ODOM_TIMEOUT_S="${APEX_RECOGNITION_TRACKER_ODOM_TIMEOUT_S:-3.0}"
export APEX_RECOGNITION_TRACKER_MIN_LOOKAHEAD_M="${APEX_RECOGNITION_TRACKER_MIN_LOOKAHEAD_M:-0.55}"
export APEX_RECOGNITION_TRACKER_MAX_LOOKAHEAD_M="${APEX_RECOGNITION_TRACKER_MAX_LOOKAHEAD_M:-1.10}"
export APEX_RECOGNITION_TRACKER_SHARP_TURN_LOOKAHEAD_MIN_M="${APEX_RECOGNITION_TRACKER_SHARP_TURN_LOOKAHEAD_MIN_M:-0.35}"
export APEX_RECOGNITION_TRACKER_ANGULAR_CMD_EMA_ALPHA="${APEX_RECOGNITION_TRACKER_ANGULAR_CMD_EMA_ALPHA:-0.08}"

export APEX_BRIDGE_MAX_SPEED_PCT="${APEX_BRIDGE_MAX_SPEED_PCT:-22}"
export APEX_BRIDGE_MIN_EFFECTIVE_SPEED_PCT="${APEX_BRIDGE_MIN_EFFECTIVE_SPEED_PCT:-10}"
export APEX_BRIDGE_LAUNCH_BOOST_SPEED_PCT="${APEX_BRIDGE_LAUNCH_BOOST_SPEED_PCT:-20}"
export APEX_BRIDGE_LAUNCH_BOOST_HOLD_S="${APEX_BRIDGE_LAUNCH_BOOST_HOLD_S:-0.25}"
export APEX_STARTUP_COMPAT="${APEX_STARTUP_COMPAT:-safe}"
export APEX_STAGGERED_STARTUP="${APEX_STAGGERED_STARTUP:-1}"
export APEX_SERIAL_WARMUP_S="${APEX_SERIAL_WARMUP_S:-2.0}"
export APEX_LIDAR_STARTUP_SETTLE_S="${APEX_LIDAR_STARTUP_SETTLE_S:-6.0}"
export APEX_NODE_STARTUP_STAGGER_S="${APEX_NODE_STARTUP_STAGGER_S:-0.8}"
export APEX_RAW_POSTCHECK_READY_DELAY_S="${APEX_RAW_POSTCHECK_READY_DELAY_S:-18}"
export APEX_RAW_POSTCHECK_TIMEOUT_S="${APEX_RAW_POSTCHECK_TIMEOUT_S:-8}"
export APEX_RAW_POSTCHECK_RETRIES="${APEX_RAW_POSTCHECK_RETRIES:-4}"
export APEX_RAW_POSTCHECK_SOFT_FAIL="${APEX_RAW_POSTCHECK_SOFT_FAIL:-1}"
export APEX_SKIP_BUILD="${APEX_SKIP_BUILD:-1}"

echo "[APEX] Fixed-map follow run: ${RUN_DIR}"
echo "[APEX] Container fixed map dir: ${APEX_FIXED_MAP_DIR}"
echo "[APEX] Tracker odom: ${APEX_RECOGNITION_TRACKER_ODOM_TOPIC}"
echo "[APEX] Tracker path: ${APEX_RECOGNITION_TRACKER_PATH_TOPIC}"

cd "${APEX_ROOT}"
exec ./tools/capture/apex_raw_capture_up.sh
